version: "3"

services:
    app:
        image: php:8.2-apache
        container_name: laravel_app
        volumes:
            - .:/var/www/html
            - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "8000:80"
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: schedule
            MYSQL_USER: eyas
            MYSQL_PASSWORD: eyas
        ports:
            - "3306:3306"
